import { eq } from "drizzle-orm";
import {
  aptitudesInRules,
  powersInRules,
  rulesetsInRules,
} from "@/drizzle/schema.ts";
import type { Db } from "@/server/database/index.ts";
import { DND35_RULESET_NAME } from "@/database/packages/dnd35/names.ts";
import { buildClassSpellLevels, seedDomains } from "@/database/packages/dnd35/seed-utils.ts";
import { ALL_DOMAINS } from "@/database/packages/dnd35/v1/domains/data.ts";
import { ALL_CLASSES } from "@/database/packages/dnd35-from-parser/generated/srd/classes/index.ts";

/**
 * Post-powers step: seed all cleric domains.
 * Runs after powers (9_powers.ts) and wizard schools (10_wizardSchools.ts).
 *
 * War Domain Weapon feats are now generated by the pipeline and seeded
 * via seedFeats in step 8 (v1/feats/index.ts).
 */
export default async function seed(db: Db) {
  const [ruleset] = await db
    .select({ id: rulesetsInRules.id })
    .from(rulesetsInRules)
    .where(eq(rulesetsInRules.name, DND35_RULESET_NAME));
  if (!ruleset) throw new Error(`Ruleset "${DND35_RULESET_NAME}" not found`);

  const [aptitudes, powers] = await Promise.all([
    db.select({ id: aptitudesInRules.id, name: aptitudesInRules.name })
      .from(aptitudesInRules)
      .where(eq(aptitudesInRules.rulesetId, ruleset.id)),
    db.select({ id: powersInRules.id, name: powersInRules.name })
      .from(powersInRules)
      .where(eq(powersInRules.rulesetId, ruleset.id)),
  ]);

  const aptMap = Object.fromEntries(aptitudes.map((a) => [a.name, a.id]));
  const powerMap = Object.fromEntries(powers.map((p) => [p.name, p.id]));

  await seedDomains(db, ruleset.id, ALL_DOMAINS, {
    aptMap,
    powerMap,
    clericDomainAptId: aptMap["Cleric Domain"],
    clericSpellLevels: buildClassSpellLevels(ALL_CLASSES)["Cleric"],
  });
}
