import { existsSync, mkdirSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";

import References from "@/database/packages/dnd35-from-parser/tools/references/References.ts";
import { CORE_BOOK } from "@/database/packages/dnd35-from-parser/tools/vocabulary/books.ts";

import { ITEM_FILES, ITEMS_INDEX } from "./bookLayout.ts";
import type { DeclaredType } from "./code/BaseCodeFile.ts";
import { CodeFile } from "./code/CodeFile.ts";

/** What a generated file's opening comment says first. */
const GENERATED = "Auto-generated by the SRD pipeline (`bun run parser:generate`): do not edit it by hand.";

/**
 * A generator's core, which its concerns (`concerns/`) build on: the folder it writes to (generated/, or a test's),
 * whether it logs what it does, the files it wrote, which a book's indexes list and the files it no longer makes
 * aren't, and what several kinds of files are written with.
 */
export class BaseGenerator {
  constructor(
    readonly dir: string,
    readonly quiet: boolean,
  ) {}

  /** The files the generator wrote, by path. */
  private readonly written = new Set<string>();

  /**
   * Whether a book copies feats and spells from the core rules (cowFeats.ts, cowSpells.ts): an extension with classes.
   * The core rules are what extensions copy from.
   */
  protected copiesFromCore(book: string): boolean {
    return book !== CORE_BOOK && References.loadClasses(book).length > 0;
  }

  /** Logs what the generator does, unless it's quiet. */
  protected log(message: string) {
    if (!this.quiet) console.log(message);
  }

  /**
   * Removes the files of a book's folder the generator didn't write: those it no longer makes (a skipped class's, a
   * spell level's without spells, an empty feat pool's).
   */
  protected removeUnwritten(book: string) {
    const folder = join(this.dir, book);
    if (!existsSync(folder)) return;
    const files = readdirSync(folder, { recursive: true, withFileTypes: true })
      .filter((entry) => entry.isFile())
      .map((entry) => join(entry.parentPath, entry.name));
    for (const file of files.filter((path) => !this.written.has(path)).sort()) {
      rmSync(file);
      this.log(`Removed: ${relative(this.dir, file)}`);
    }
  }

  /**
   * Writes a generated file, creating its folder: its code under the opening comment every generated file has, which
   * lists what's left to review in it (`notes`, a class's).
   */
  protected write(path: string, code: string, notes: string[] = []) {
    const header =
      notes.length === 0
        ? [`/** ${GENERATED} */`]
        : ["/**", ` * ${GENERATED}`, " *", " * To review:", ...notes.map((note) => ` * - ${note}`), " */"];
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, [...header, "", code].join("\n"));
    this.written.add(path);
    this.log(`Generated: ${relative(this.dir, path)}`);
  }

  /** Writes a book's items' index (items/index.ts): every item file the generator wrote of it, mundane or magic. */
  protected writeItemIndex(book: string) {
    const files = ITEM_FILES.filter(({ path }) => this.wrote(book, join(dirname(ITEMS_INDEX), path)));
    if (files.length === 0) return;
    const file = new CodeFile();
    file.lines.push(...files.map(({ path, list }) => `export { ${list} } from "./${path}";`), ``);
    this.write(join(this.dir, book, ITEMS_INDEX), file.code());
  }

  /**
   * Writes a file of one list, `list` of `type` (a content type, or text): each of `seeds` written as code by `write`
   * (a seed's `CodeFile` writer, `file.race(race)`), the file's imports what they use.
   */
  protected writeList<T>(
    path: string,
    list: string,
    type: DeclaredType | "string",
    seeds: T[],
    write: (file: CodeFile, seed: T) => string | string[],
  ) {
    const file = new CodeFile();
    file.list(
      list,
      type,
      seeds.flatMap((seed) => write(file, seed)),
    );
    this.write(path, file.code());
  }

  /** Whether the generator wrote the book's file at `path` (in its folder). */
  protected wrote(book: string, path: string): boolean {
    return this.written.has(join(this.dir, book, path));
  }
}
