import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";

import { CodeFile } from "@/database/packages/dnd35-from-parser/tools/generator/code/CodeFile.ts";
import { formatImport, type ImportTable } from "@/database/packages/dnd35-from-parser/tools/generator/code/imports.ts";
import { quote } from "@/database/packages/dnd35-from-parser/tools/generator/code/literals.ts";
import { CORE_BOOK } from "@/database/packages/dnd35-from-parser/tools/references/files.ts";
import ReferenceLoader from "@/database/packages/dnd35-from-parser/tools/references/ReferenceLoader.ts";

/** What a generated file's opening comment says first. */
const GENERATED = "Auto-generated by the SRD pipeline (`bun run parser:generate`): do not edit it by hand.";

/** The files a book's items/ can hold, each with the list it exports, in the order the items' index lists them. */
const ITEM_FILES = [
  ["weapons.ts", "SIMPLE_WEAPONS"],
  ["martial.ts", "MARTIAL_WEAPONS"],
  ["exotic.ts", "EXOTIC_WEAPONS"],
  ["armor.ts", "ARMOR"],
  ["shields.ts", "SHIELDS"],
  ["goods.ts", "GOODS"],
  ["magic-armor.ts", "MAGIC_ARMOR"],
  ["magic-shields.ts", "MAGIC_SHIELDS"],
  ["magic-weapons.ts", "MAGIC_WEAPONS"],
  ["wondrous-items.ts", "WONDROUS_ITEMS"],
  ["rings.ts", "RINGS"],
  ["rods.ts", "RODS"],
  ["staffs.ts", "STAFFS"],
];

/** The builders an item file can import, in the order its import lists them. */
const ITEM_IMPORTS: ImportTable = [
  [
    "@/database/packages/dnd35/content/items/proficiencies.ts",
    [
      "simple",
      "martial",
      "exotic",
      "HEAVY_ARMOR_PROF",
      "LIGHT_ARMOR_PROF",
      "MEDIUM_ARMOR_PROF",
      "SHIELD_PROF",
      "TOWER_SHIELD_PROF",
    ],
  ],
  [
    "@/database/packages/dnd35/content/items/properties.ts",
    ["weaponProperties", "armorProperties", "shieldProperties"],
  ],
];

/** Where the seed type an index file lists comes from. */
const SEED_TYPE_MODULES = {
  ClassSeed: "@/database/packages/dnd35/content/classes/types.ts",
  FeatSeed: "@/database/packages/dnd35/content/feats/types.ts",
  SpellSeed: "@/database/packages/dnd35/content/spells/types.ts",
};

/**
 * A generator's core, which its concerns (`concerns/`) build on: the folder it writes to (generated/, or a test's),
 * whether it logs what it does, and what several kinds of files are written with.
 */
export class BaseGenerator {
  constructor(
    readonly dir: string,
    readonly quiet: boolean,
  ) {}

  /** The proficiency an armor of a category takes, by the builder's name. */
  protected armorProficiencyOf(category: string | undefined): string {
    if (category === "Medium") return "MEDIUM_ARMOR_PROF";
    if (category === "Heavy") return "HEAVY_ARMOR_PROF";
    return "LIGHT_ARMOR_PROF";
  }

  /**
   * Whether a book copies feats and spells from the core rules (cowFeats.ts, cowSpells.ts): an extension with classes.
   * The core rules are what extensions copy from.
   */
  protected copiesFromCore(book: string): boolean {
    return book !== CORE_BOOK && ReferenceLoader.loadClasses(book).length > 0;
  }

  /** An index file's head: its header, the seed type's import, and the import of each file's list. */
  protected indexHead(
    seedType: keyof typeof SEED_TYPE_MODULES,
    lists: { constName: string; file: string }[],
  ): string[] {
    return [
      `import type { ${seedType} } from "${SEED_TYPE_MODULES[seedType]}";`,
      ``,
      ...lists.map(({ constName, file }) => formatImport([constName], `./${file}`)),
      ``,
    ];
  }

  /** An exported list of `seedType`, an item per line. */
  protected listExport(name: string, seedType: string, items: string[]): string[] {
    return [`export const ${name}: ${seedType}[] = [`, ...items.map((item) => `  ${item},`), `];`, ``];
  }

  /** Logs what the generator does, unless it's quiet. */
  protected log(message: string) {
    if (!this.quiet) console.log(message);
  }

  /**
   * Writes a generated file, creating its folder: its code under the opening comment every generated file has, which
   * lists what's left to review in it (`notes`, a class's).
   */
  protected write(path: string, code: string, notes: string[] = []) {
    const header =
      notes.length === 0
        ? [`/** ${GENERATED} */`]
        : ["/**", ` * ${GENERATED}`, " *", " * To review:", ...notes.map((note) => ` * - ${note}`), " */"];
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, [...header, "", code].join("\n"));
    this.log(`Generated: ${relative(this.dir, path)}`);
  }

  /**
   * Writes a file of items, `constName`: each its name and description, then the lines `fields` gives. `uses` are the
   * builders it takes from content/items/proficiencies.ts and content/items/properties.ts.
   */
  protected writeItemFile<T extends { name: string; description: string }>(
    path: string,
    constName: string,
    uses: string[],
    items: T[],
    fields: (item: T) => string[],
  ) {
    const file = new CodeFile(ITEM_IMPORTS);
    for (const name of uses) file.uses.add(name);
    file.lines.push(
      `export const ${constName}: ItemSeed[] = [`,
      ...items.flatMap((item) => [
        `  {`,
        `    name: ${quote(item.name)},`,
        `    description: ${quote(item.description)},`,
        ...fields(item).map((line) => `    ${line}`),
        `  },`,
      ]),
      `];`,
      ``,
    );
    this.write(path, file.code([`import type { ItemSeed } from "@/database/packages/dnd35/content/items/types.ts";`]));
  }

  /**
   * Writes a book's items' index (items/index.ts): every item file it has, mundane or magic, whichever reference was
   * generated last.
   */
  protected writeItemIndex(outDir: string) {
    const lines = [
      ...ITEM_FILES.filter(([file]) => existsSync(join(outDir, file))).map(
        ([file, name]) => `export { ${name} } from "./${file}";`,
      ),
      ``,
    ];
    this.write(join(outDir, "index.ts"), lines.join("\n"));
  }
}
