import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";

import { CORE_BOOK } from "@/database/packages/dnd35-from-parser/tools/references/files.ts";
import ReferenceLoader from "@/database/packages/dnd35-from-parser/tools/references/ReferenceLoader.ts";

import { ITEM_FILES, ITEMS_INDEX } from "./bookLayout.ts";
import type { DeclaredType } from "./code/BaseCodeFile.ts";
import { CodeFile } from "./code/CodeFile.ts";

/** What a generated file's opening comment says first. */
const GENERATED = "Auto-generated by the SRD pipeline (`bun run parser:generate`): do not edit it by hand.";

/**
 * A generator's core, which its concerns (`concerns/`) build on: the folder it writes to (generated/, or a test's),
 * whether it logs what it does, and what several kinds of files are written with.
 */
export class BaseGenerator {
  constructor(
    readonly dir: string,
    readonly quiet: boolean,
  ) {}

  /**
   * Whether a book copies feats and spells from the core rules (cowFeats.ts, cowSpells.ts): an extension with classes.
   * The core rules are what extensions copy from.
   */
  protected copiesFromCore(book: string): boolean {
    return book !== CORE_BOOK && ReferenceLoader.loadClasses(book).length > 0;
  }

  /** Logs what the generator does, unless it's quiet. */
  protected log(message: string) {
    if (!this.quiet) console.log(message);
  }

  /**
   * Writes a generated file, creating its folder: its code under the opening comment every generated file has, which
   * lists what's left to review in it (`notes`, a class's).
   */
  protected write(path: string, code: string, notes: string[] = []) {
    const header =
      notes.length === 0
        ? [`/** ${GENERATED} */`]
        : ["/**", ` * ${GENERATED}`, " *", " * To review:", ...notes.map((note) => ` * - ${note}`), " */"];
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, [...header, "", code].join("\n"));
    this.log(`Generated: ${relative(this.dir, path)}`);
  }

  /**
   * Writes a book's items' index (items/index.ts): every item file it has, mundane or magic, whichever reference was
   * generated last.
   */
  protected writeItemIndex(book: string) {
    const outDir = dirname(join(this.dir, book, ITEMS_INDEX));
    const file = new CodeFile();
    file.lines.push(
      ...ITEM_FILES.filter(({ path }) => existsSync(join(outDir, path))).map(
        ({ path, list }) => `export { ${list} } from "./${path}";`,
      ),
      ``,
    );
    this.write(join(this.dir, book, ITEMS_INDEX), file.code());
  }

  /**
   * Writes a file of one list, `list` of `type` (a content type, or text): each of `seeds` written as code by `write`
   * (a seed's `CodeFile` writer, `file.race(race)`), the file's imports what they use.
   */
  protected writeList<T>(
    path: string,
    list: string,
    type: DeclaredType | "string",
    seeds: T[],
    write: (file: CodeFile, seed: T) => string | string[],
  ) {
    const file = new CodeFile();
    file.list(
      list,
      type,
      seeds.flatMap((seed) => write(file, seed)),
    );
    this.write(path, file.code());
  }
}
