import {
  closeSync,
  cpSync,
  existsSync,
  mkdirSync,
  openSync,
  readdirSync,
  renameSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, relative } from "node:path";

const BASE_DIR = join(import.meta.dirname!, "../../");

/** The repo's formatter, its pinned version, and its config, which a generated tree is laid out by. */
const FORMATTER = join(BASE_DIR, "../../../node_modules/.bin/oxfmt");
const FORMATTER_CONFIG = join(BASE_DIR, "../../../.oxfmtrc.json");

/** What a generated file's opening comment says first. */
const GENERATED = "Auto-generated by the SRD pipeline (`bun run parser:generate`): do not edit it by hand.";

/** The repo's linter and its config, whose `member-order` sorts a generated tree's declarations. */
const LINTER = join(BASE_DIR, "../../../node_modules/.bin/oxlint");

const LINTER_CONFIG = join(BASE_DIR, "../../../.oxlintrc.json");

/**
 * The folder a generation writes (generated/, or a test's), and what a generation wrote in it, which a book's indexes
 * list and the files it no longer makes aren't. A generation runs in a copy of the folder, which takes the folder's
 * place only once the generation succeeded and the copy is laid out as the rest of the repo is (`generateAtomically`):
 * generated/ is never half-written.
 */
export class GeneratedFolder {
  constructor(
    readonly dir: string,
    readonly quiet: boolean,
  ) {}

  /**
   * Lays a generated tree out as the rest of the repo is, by the repo's configs wherever the tree is written, so what
   * the generator writes passes the lint and the format check: its declarations sorted by `member-order` (with its
   * suggestions: a generated value builds data, whatever order it runs in), then formatted by `oxfmt`.
   */
  private static format(dir: string) {
    // Its files by name: the repo ignores the copy a generation writes (`.gitignore`), and oxfmt a folder it ignores
    const files = readdirSync(dir, { recursive: true, withFileTypes: true })
      .filter((entry) => entry.isFile() && entry.name.endsWith(".ts"))
      .map((entry) => join(entry.parentPath, entry.name));
    const sorted = Bun.spawnSync(
      [LINTER, "-c", LINTER_CONFIG, "-A", "all", "-D", "arkyvree/member-order", "--fix", "--fix-suggestions", ...files],
      { stdout: "pipe", stderr: "pipe" },
    );
    if (sorted.exitCode !== 0) throw new Error(`Sorting ${dir} failed: ${sorted.stdout.toString()}`);
    const formatted = Bun.spawnSync([FORMATTER, "-c", FORMATTER_CONFIG, ...files], {
      stdout: "pipe",
      stderr: "pipe",
    });
    if (formatted.exitCode !== 0) throw new Error(`Formatting ${dir} failed: ${formatted.stderr.toString()}`);
  }

  /**
   * Takes `lock`, a file only one process can create: a second generation on the same folder would work in the first's
   * copy.
   */
  private static lock(lock: string): number {
    try {
      return openSync(lock, "wx");
    } catch (error) {
      if (!(error instanceof Error && "code" in error && error.code === "EEXIST")) throw error;
      throw new Error(`Another generation is running on this folder: delete ${lock} if it was killed`);
    }
  }

  /**
   * Runs a generation in a copy of `dir`, which takes `dir`'s place only when the generation reports no failure: a
   * failed one leaves `dir` as it was rather than half-written. The copy sits next to `dir`, so the swap is a rename,
   * and one generation runs on `dir` at a time.
   */
  static generateAtomically(dir: string, generate: (copy: string) => string[]): string[] {
    const copy = `${dir}.next`;
    const previous = `${dir}.previous`;
    const lock = `${dir}.lock`;
    const lockFd = GeneratedFolder.lock(lock);
    try {
      // A run killed mid-swap left the tree only as `previous`
      if (!existsSync(dir) && existsSync(previous)) renameSync(previous, dir);
      rmSync(copy, { recursive: true, force: true });
      rmSync(previous, { recursive: true, force: true });
      cpSync(dir, copy, { recursive: true });
      const failures = generate(copy);
      if (failures.length === 0) {
        GeneratedFolder.format(copy);
        renameSync(dir, previous);
        try {
          renameSync(copy, dir);
        } catch (error) {
          renameSync(previous, dir);
          throw error;
        }
        rmSync(previous, { recursive: true, force: true });
      }
      return failures;
    } finally {
      rmSync(copy, { recursive: true, force: true });
      closeSync(lockFd);
      rmSync(lock, { force: true });
    }
  }

  /** The files the generation wrote, by their path in the folder. */
  private readonly written = new Set<string>();

  /** Logs what the generation does, unless it's quiet. */
  log(message: string) {
    if (!this.quiet) console.log(message);
  }

  /**
   * Removes the files of `folder` (a book's) the generation didn't write: those it no longer makes (a skipped class's,
   * a spell level's without spells, an empty feat pool's).
   */
  removeUnwritten(folder: string) {
    const dir = join(this.dir, folder);
    if (!existsSync(dir)) return;
    const files = readdirSync(dir, { recursive: true, withFileTypes: true })
      .filter((entry) => entry.isFile())
      .map((entry) => relative(this.dir, join(entry.parentPath, entry.name)));
    for (const file of files.filter((path) => !this.written.has(path)).sort()) {
      rmSync(join(this.dir, file));
      this.log(`Removed: ${file}`);
    }
  }

  /**
   * Writes a generated file at `path` in the folder, creating its folder: its code under the opening comment every
   * generated file has, which lists what's left to review in it (`notes`, a class's).
   */
  write(path: string, code: string, notes: string[] = []) {
    const header =
      notes.length === 0
        ? [`/** ${GENERATED} */`]
        : ["/**", ` * ${GENERATED}`, " *", " * To review:", ...notes.map((note) => ` * - ${note}`), " */"];
    const file = join(this.dir, path);
    mkdirSync(dirname(file), { recursive: true });
    writeFileSync(file, [...header, "", code].join("\n"));
    this.written.add(path);
    this.log(`Generated: ${path}`);
  }

  /** Whether the generation wrote the file at `path` in the folder. */
  wrote(path: string): boolean {
    return this.written.has(path);
  }
}
