import {
  closeSync,
  cpSync,
  existsSync,
  mkdirSync,
  openSync,
  readdirSync,
  readFileSync,
  renameSync,
  rmSync,
  unlinkSync,
  writeFileSync,
} from "node:fs";
import { basename, dirname, join, relative } from "node:path";

import { collectAptitudes } from "@/database/packages/dnd35-from-parser/tools/buildSeeds/aptitudes.ts";
import {
  classSpells,
  inheritedLevel,
  inheritedLists,
} from "@/database/packages/dnd35-from-parser/tools/buildSeeds/classes.ts";
import { bookDomainSeeds } from "@/database/packages/dnd35-from-parser/tools/buildSeeds/domains.ts";
import { buildItemSeeds } from "@/database/packages/dnd35-from-parser/tools/buildSeeds/items.ts";
import { buildMagicItemSeeds } from "@/database/packages/dnd35-from-parser/tools/buildSeeds/magicItems.ts";
import { buildRaceSeeds } from "@/database/packages/dnd35-from-parser/tools/buildSeeds/races.ts";
import { buildSpellSeeds } from "@/database/packages/dnd35-from-parser/tools/buildSeeds/spells.ts";
import { buildWizardSchoolSeeds } from "@/database/packages/dnd35-from-parser/tools/buildSeeds/wizardSchools.ts";
import {
  featLines,
  importLines,
  type ImportTable,
  listField,
  quote,
  requirementImports,
  stringifyModifier,
  stringifyProperty,
  toConstName,
} from "@/database/packages/dnd35-from-parser/tools/generator/codegen.ts";
import {
  generateFeatSeeds as generateClassFeatSeeds,
  generateClassSeed,
} from "@/database/packages/dnd35-from-parser/tools/generator/generators/class.ts";
import {
  coreSystemFeats,
  featAptitudeSources,
  generateFavoredEnemyFeats,
  generateFeatSeeds,
} from "@/database/packages/dnd35-from-parser/tools/generator/generators/feat.ts";
import { generateSpellFiles } from "@/database/packages/dnd35-from-parser/tools/generator/generators/spell.ts";
import { classReferences, loadReference } from "@/database/packages/dnd35-from-parser/tools/references.ts";
import {
  discoverRefs,
  type parseCliArgs,
  REFERENCE_DIR,
  referenceBooks,
  toCamelCase,
} from "@/database/packages/dnd35-from-parser/tools/shared.ts";
import type {
  ClassReference,
  FeatReference,
  ItemReference,
  MagicItemReference,
  RaceReference,
  SpellReference,
  WizardSchoolReference,
} from "@/database/packages/dnd35-from-parser/tools/types.ts";
import type { DomainDefinition, FeatSeed } from "@/database/packages/dnd35/content/types.ts";
import { getArmorDefinition, getShieldDefinition } from "@/server/rulesets/dnd3.5/hooks/generators/armorGenerator.ts";
import { ARMOR_PROFICIENCY } from "@/shared/dnd3.5/properties/index.ts";

/** Where a generation writes (generated/, or a test's folder), and whether it logs what it does. */
type Output = { dir: string; quiet: boolean };

const BASE_DIR = join(import.meta.dirname!, "../../");

/** The first line of an index or data file the generator writes. */
const GENERATED_HEADER = `// Auto-generated by the SRD pipeline — do not edit manually`;

/** The builders an item file can import, in the order its import lists them. */
const ITEM_IMPORTS: ImportTable = [
  [
    "@/database/packages/dnd35/content/items.ts",
    [
      "simple",
      "martial",
      "exotic",
      "weaponProperties",
      "armorProperties",
      "HEAVY_ARMOR_PROF",
      "LIGHT_ARMOR_PROF",
      "MEDIUM_ARMOR_PROF",
      "shieldProperties",
      "SHIELD_PROF",
      "TOWER_SHIELD_PROF",
    ],
  ],
];

export const GENERATED_DIR = join(BASE_DIR, "generated");

function getShieldProf(generatorName: string): string {
  const def = getShieldDefinition(generatorName);
  if (def?.shieldType === "Tower") return "TOWER_SHIELD_PROF";
  return "SHIELD_PROF";
}

/** An exported list of `seedType`, an item per line. */
function listExport(name: string, seedType: string, items: string[]): string[] {
  return [`export const ${name}: ${seedType}[] = [`, ...items.map((item) => `  ${item},`), `];`, ``];
}

/** The proficiency an armor of a category takes, by the builder's name. */
function armorProficiencyOf(category: string | undefined): string {
  if (category === "Medium") return "MEDIUM_ARMOR_PROF";
  if (category === "Heavy") return "HEAVY_ARMOR_PROF";
  return "LIGHT_ARMOR_PROF";
}

function getArmorProf(generatorName: string): string {
  return armorProficiencyOf(getArmorDefinition(generatorName)?.armorType);
}

/** The weight of each weapon, armor and shield the book's item reference seeds, by name: what an item made from one weighs. */
function baseItemWeights(referenceDir: string): Record<string, string> {
  const path = join(referenceDir, "items.json");
  if (!existsSync(path)) return {};
  const seeds = buildItemSeeds(loadReference(path, "item"));
  const bases = [
    ...seeds.simpleWeapons,
    ...seeds.martialWeapons,
    ...seeds.exoticWeapons,
    ...seeds.armor,
    ...seeds.shields,
  ];
  return Object.fromEntries(bases.map((item) => [item.name, item.weight]));
}

/**
 * Whether a book copies feats and spells from the core rules (cowFeats.ts, cowSpells.ts): an extension with classes.
 * The core rules are what extensions copy from.
 */
function copiesFromCore(book: string): boolean {
  return book !== "srd" && classReferences(book).length > 0;
}

/** A book's domains file (data.ts). */
function domainsCode(seeds: DomainDefinition[]): string {
  const lines: string[] = [];
  lines.push(`export const ALL_DOMAINS: DomainDefinition[] = [`);
  for (const d of seeds) {
    lines.push(`  {`);
    lines.push(`    name: ${quote(d.name)},`);
    lines.push(`    description: ${quote(d.description)},`);
    lines.push(...listField("modifiers", (d.modifiers ?? []).map(stringifyModifier), "    "));
    lines.push(`    spells: [`);
    for (const s of d.spells) {
      lines.push(`      { name: ${quote(s.name)}, level: ${s.level} },`);
    }
    lines.push(`    ],`);
    lines.push(`  },`);
  }
  lines.push(`];`);
  lines.push(``);
  return [`import type { DomainDefinition } from "@/database/packages/dnd35/content/types.ts";`, ``, ...lines].join(
    "\n",
  );
}

/** An index file's head: its header, the seed type's import, and the import of each file's list. */
function indexHead(seedType: string, lists: { constName: string; file: string }[]): string[] {
  return [
    GENERATED_HEADER,
    `import type { ${seedType} } from "@/database/packages/dnd35/content/types.ts";`,
    ``,
    ...lists.map(({ constName, file }) => `import { ${constName} } from "./${file}";`),
    ``,
  ];
}

/** Takes `lock`, a file only one process can create: a second generation on the same folder would work in the first's copy. */
function takeLock(lock: string): number {
  try {
    return openSync(lock, "wx");
  } catch (error) {
    if (!(error instanceof Error && "code" in error && error.code === "EEXIST")) throw error;
    throw new Error(`Another generation is running on this folder: delete ${lock} if it was killed`);
  }
}

/** Writes a generated file, creating its folder. */
function writeGenerated(out: Output, path: string, code: string) {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, code);
  if (!out.quiet) console.log(`Generated: ${relative(out.dir, path)}`);
}

/** Writes a book's domain pool feats (domainFeats.ts): one list, the feats grouped by their pool's aptitude. */
function generateDomainFeatPool(out: Output, feats: FeatSeed[], book: string) {
  const uses = new Set<string>();
  const lines = [
    `export const DOMAIN_POOL_FEATS: FeatSeed[] = [`,
    ...[...Map.groupBy(feats, (feat) => feat.aptitudes[0]).values()].flat().flatMap((feat) => featLines(feat, uses)),
    `];`,
    ``,
  ];

  const head = [
    GENERATED_HEADER,
    `import type { FeatSeed } from "@/database/packages/dnd35/content/types.ts";`,
    ...requirementImports(uses),
    ``,
  ];
  writeGenerated(out, join(out.dir, book, "feats", "domainFeats.ts"), [...head, ...lines].join("\n"));
}

function generateItemIndex(out: Output, outDir: string) {
  const lines: string[] = [];
  lines.push(GENERATED_HEADER);
  lines.push(`export { SIMPLE_WEAPONS } from "./weapons.ts";`);
  lines.push(`export { MARTIAL_WEAPONS } from "./martial.ts";`);
  lines.push(`export { EXOTIC_WEAPONS } from "./exotic.ts";`);
  lines.push(`export { ARMOR } from "./armor.ts";`);
  lines.push(`export { SHIELDS } from "./shields.ts";`);
  lines.push(`export { GOODS } from "./goods.ts";`);
  lines.push(``);
  const outPath = join(outDir, "index.ts");
  writeGenerated(out, outPath, lines.join("\n"));
}

function generateItemIndexWithMagic(out: Output, outDir: string) {
  const lines: string[] = [];
  lines.push(GENERATED_HEADER);
  // Mundane items
  if (existsSync(join(outDir, "weapons.ts"))) lines.push(`export { SIMPLE_WEAPONS } from "./weapons.ts";`);
  if (existsSync(join(outDir, "martial.ts"))) lines.push(`export { MARTIAL_WEAPONS } from "./martial.ts";`);
  if (existsSync(join(outDir, "exotic.ts"))) lines.push(`export { EXOTIC_WEAPONS } from "./exotic.ts";`);
  if (existsSync(join(outDir, "armor.ts"))) lines.push(`export { ARMOR } from "./armor.ts";`);
  if (existsSync(join(outDir, "shields.ts"))) lines.push(`export { SHIELDS } from "./shields.ts";`);
  if (existsSync(join(outDir, "goods.ts"))) lines.push(`export { GOODS } from "./goods.ts";`);
  // Magic items
  if (existsSync(join(outDir, "magic-armor.ts"))) lines.push(`export { MAGIC_ARMOR } from "./magic-armor.ts";`);
  if (existsSync(join(outDir, "magic-shields.ts"))) lines.push(`export { MAGIC_SHIELDS } from "./magic-shields.ts";`);
  if (existsSync(join(outDir, "magic-weapons.ts"))) lines.push(`export { MAGIC_WEAPONS } from "./magic-weapons.ts";`);
  if (existsSync(join(outDir, "wondrous-items.ts")))
    lines.push(`export { WONDROUS_ITEMS } from "./wondrous-items.ts";`);
  if (existsSync(join(outDir, "rings.ts"))) lines.push(`export { RINGS } from "./rings.ts";`);
  if (existsSync(join(outDir, "rods.ts"))) lines.push(`export { RODS } from "./rods.ts";`);
  if (existsSync(join(outDir, "staffs.ts"))) lines.push(`export { STAFFS } from "./staffs.ts";`);
  lines.push(``);
  const outPath = join(outDir, "index.ts");
  writeGenerated(out, outPath, lines.join("\n"));
}

function generateRace(out: Output, ref: RaceReference, book: string) {
  const seeds = buildRaceSeeds(ref);
  if (!out.quiet) console.log(`Built ${seeds.length} race seeds`);

  // Generate data.ts
  const lines: string[] = [];
  lines.push(`export const ALL_RACES: RaceDefinition[] = [`);
  for (const r of seeds) {
    lines.push(`  {`);
    lines.push(`    name: ${quote(r.name)},`);
    lines.push(`    description: ${quote(r.description)},`);
    lines.push(`    size: ${quote(r.size)},`);
    lines.push(`    baseSpeed: ${r.baseSpeed},`);
    lines.push(...listField("modifiers", (r.modifiers ?? []).map(stringifyModifier), "    "));
    lines.push(...listField("properties", (r.properties ?? []).map(stringifyProperty), "    "));
    lines.push(`  },`);
  }
  lines.push(`];`);
  lines.push(``);

  const head = [`import type { RaceDefinition } from "@/database/packages/dnd35/content/types.ts";`, ``];
  writeGenerated(out, join(out.dir, book, "races", "data.ts"), [...head, ...lines].join("\n"));

  if (!out.quiet) console.log(`\nDone!`);
}

function generateWizardSchool(out: Output, ref: WizardSchoolReference, book: string) {
  const seeds = buildWizardSchoolSeeds(ref);
  if (!out.quiet) console.log(`Built ${seeds.length} wizard school seeds`);

  // Generate data.ts
  const lines: string[] = [];
  lines.push(`import type { WizardSchoolDefinition } from "@/database/packages/dnd35/content/types.ts";`);
  lines.push(``);
  lines.push(`export const WIZARD_SCHOOLS: WizardSchoolDefinition[] = [`);
  for (const s of seeds) {
    lines.push(`  {`);
    lines.push(`    name: ${quote(s.name)},`);
    lines.push(`    description: ${quote(s.description)},`);
    lines.push(`    prohibitedSchoolCount: ${s.prohibitedSchoolCount},`);
    lines.push(`  },`);
  }
  lines.push(`];`);
  lines.push(``);

  writeGenerated(out, join(out.dir, book, "wizard-schools", "data.ts"), lines.join("\n"));

  if (!out.quiet) console.log(`\nDone!`);
}

/** Regenerate aptitudes.ts for a book from reference JSONs: its feats', and the core rules' system feats. */
function regenerateAptitudes(out: Output, book: string) {
  const featRefPath = join(REFERENCE_DIR, book, "feats.json");
  const feats = [
    ...(existsSync(featRefPath) ? featAptitudeSources(loadReference(featRefPath, "feat")) : []),
    ...(book === "srd"
      ? coreSystemFeats(
          buildWizardSchoolSeeds(loadReference(join(REFERENCE_DIR, "srd", "wizardSchools.json"), "wizardSchool")),
        )
      : []),
  ];

  const aptitudes = collectAptitudes(feats, book);

  const aptLines: string[] = [];
  aptLines.push(GENERATED_HEADER);
  aptLines.push(``);
  aptLines.push(`export const ALL_APTITUDES: string[] = [`);
  for (const apt of aptitudes) {
    aptLines.push(`  ${quote(apt)},`);
  }
  aptLines.push(`];`);
  aptLines.push(``);
  writeGenerated(out, join(out.dir, book, "aptitudes.ts"), aptLines.join("\n"));
}

/** Regenerate index.ts for an extension's book: its content, as the extension seeds it. */
function regenerateBookIndex(out: Output, book: string) {
  const dir = join(out.dir, book);
  const parts: { key: string; file: string; name: string }[] = [
    { key: "aptitudes", file: "aptitudes.ts", name: "ALL_APTITUDES" },
    { key: "standaloneFeats", file: "feats/index.ts", name: "ALL_STANDALONE_FEATS" },
    { key: "classFeats", file: "feats/index.ts", name: "ALL_CLASS_FEATS" },
    { key: "cowFeats", file: "cowFeats.ts", name: "COW_FEATS" },
    { key: "spells", file: "spells/index.ts", name: "ALL_SPELLS" },
    { key: "cowSpells", file: "cowSpells.ts", name: "COW_SPELLS" },
    { key: "domains", file: "domains/data.ts", name: "ALL_DOMAINS" },
    { key: "classes", file: "classes/index.ts", name: "ALL_CLASSES" },
  ];
  const present = parts.filter((part) => existsSync(join(dir, part.file)));
  const files = [...new Set(present.map((part) => part.file))].sort();

  const lines: string[] = [];
  lines.push(GENERATED_HEADER);
  lines.push(`import type { BookContent } from "@/database/packages/dnd35/content/types.ts";`);
  for (const file of files) {
    const names = present
      .filter((part) => part.file === file)
      .map((part) => part.name)
      .sort();
    lines.push(`import { ${names.join(", ")} } from "./${file}";`);
  }
  lines.push(``);
  lines.push(`export const BOOK: BookContent = {`);
  for (const part of parts) {
    lines.push(`  ${part.key}: ${present.includes(part) ? part.name : "[]"},`);
  }
  lines.push(`};`);
  lines.push(``);

  writeGenerated(out, join(dir, "index.ts"), lines.join("\n"));
}

/** Regenerate feats/classes/index.ts for a book from all generated class feat .ts files. */
function regenerateClassFeatIndex(out: Output, book: string) {
  const classFeatDir = join(out.dir, book, "feats", "classes");
  let tsFiles: string[];
  try {
    tsFiles = readdirSync(classFeatDir)
      .filter((f) => f.endsWith(".ts") && f !== "index.ts")
      .sort();
  } catch {
    return; // no class feat files for this book
  }

  if (tsFiles.length === 0) return;

  type FeatEntry = { slug: string; constName: string };
  const entries: FeatEntry[] = [];

  for (const file of tsFiles) {
    const slug = file.replace(".ts", "");
    const content = readFileSync(join(classFeatDir, file), "utf-8");
    const match = content.match(/export const (\w+_FEATS)/);
    if (match) {
      entries.push({ slug, constName: match[1] });
    }
  }

  if (entries.length === 0) return;

  const lines = indexHead(
    "FeatSeed",
    entries.map((e) => ({ constName: e.constName, file: `${e.slug}.ts` })),
  );

  // Deduplicate: a feat like "Familiar" may appear in multiple class feat files
  lines.push(`const _allClassFeats: FeatSeed[] = [`);
  for (const e of entries) {
    lines.push(`  ...${e.constName},`);
  }
  lines.push(`];`);
  lines.push(`const _seen = new Set<string>();`);
  lines.push(`export const ALL_CLASS_FEATS: FeatSeed[] = _allClassFeats.filter((f) => {`);
  lines.push(`  if (_seen.has(f.name)) return false;`);
  lines.push(`  _seen.add(f.name);`);
  lines.push(`  return true;`);
  lines.push(`});`);
  lines.push(``);

  // Re-export individual arrays for consumers that need them
  for (const e of entries) {
    lines.push(`export { ${e.constName} };`);
  }
  lines.push(``);

  const outPath = join(classFeatDir, "index.ts");
  writeGenerated(out, outPath, lines.join("\n"));
}

/** Regenerate classes/index.ts for a book from class reference JSONs. */
function regenerateClassIndex(out: Output, book: string) {
  const classes = classReferences(book).sort((a, b) => (a.file < b.file ? -1 : 1));
  if (classes.length === 0) return; // no classes for this book

  type ClassEntry = { slug: string; constName: string; isBase: boolean };
  const entries: ClassEntry[] = [];

  for (const { ref } of classes) {
    if (!ref.raw?.name) continue;
    const slug = toCamelCase(ref.raw.name);
    const levels = ref.detected?.levels ?? 0;
    entries.push({
      slug,
      constName: toConstName(ref.raw.name),
      isBase: levels === 20,
    });
  }

  const names = (list: ClassEntry[]) => list.map((e) => e.constName);
  const baseEntries = entries.filter((e) => e.isBase);
  const prestigeEntries = entries.filter((e) => !e.isBase);
  const lines = [
    ...indexHead(
      "ClassSeed",
      entries.map((e) => ({ constName: e.constName, file: `${e.slug}.ts` })),
    ),
    ...listExport("ALL_CLASSES", "ClassSeed", names(entries)),
    ...(baseEntries.length > 0 ? listExport("ALL_BASE_CLASSES", "ClassSeed", names(baseEntries)) : []),
    ...(prestigeEntries.length > 0 ? listExport("ALL_PRESTIGE_CLASSES", "ClassSeed", names(prestigeEntries)) : []),
  ];

  const genClassDir = join(out.dir, book, "classes");
  const outPath = join(genClassDir, "index.ts");
  writeGenerated(out, outPath, lines.join("\n"));
}

/** Regenerate cowFeats.ts for a book from bonusFeatLists in class reference JSONs.
 *  Only emits entries for feats that don't already exist in the book's own feat pool
 *  (i.e. cross-book references that actually need COW). Same-book feats already get
 *  their aptitudes added directly by the feat generator. */
function regenerateCowFeats(out: Output, book: string) {
  if (!copiesFromCore(book)) return;
  const classes = classReferences(book);

  // Load the book's own raw feat names — these already get aptitudes via the feat generator
  const bookFeats = new Set<string>();
  const bookFeatsPath = join(REFERENCE_DIR, book, "feats.json");
  if (existsSync(bookFeatsPath)) {
    const ref = loadReference(bookFeatsPath, "feat");
    for (const feat of ref.raw) bookFeats.add(feat.name);
  }

  // Also collect class feature seed names — these are generated as feats by the class feat generator
  const classFeatureNames = new Set<string>();
  for (const { ref } of classes) {
    for (const feat of Object.values(ref.mapping.features)) {
      if (feat.seedName) classFeatureNames.add(feat.seedName);
    }
  }

  type CowEntry = { feat: string; requirements: { className: string; level: number }[]; aptitudes: string[] };
  const entries: CowEntry[] = [];

  for (const { ref } of classes) {
    const bonusFeatLists = ref.overrides?.bonusFeatLists ?? ref.detected?.bonusFeatLists;
    if (!bonusFeatLists?.length) continue;

    for (const list of bonusFeatLists) {
      for (const feat of list.feats) {
        // Skip feats that exist in this book's own feat pool or as class features —
        // the feat generator already adds the aptitude directly
        if (bookFeats.has(feat) || classFeatureNames.has(feat)) continue;
        entries.push({ feat, requirements: [], aptitudes: [list.aptitude] });
      }
    }
  }

  const outPath = join(out.dir, book, "cowFeats.ts");

  // Deduplicate: a feat might appear in multiple lists
  const deduped = new Map<string, CowEntry>();
  for (const entry of entries) {
    const existing = deduped.get(entry.feat);
    if (existing) {
      for (const apt of entry.aptitudes) {
        if (!existing.aptitudes.includes(apt)) existing.aptitudes.push(apt);
      }
    } else {
      deduped.set(entry.feat, { ...entry });
    }
  }

  const lines: string[] = [];
  lines.push(GENERATED_HEADER);
  lines.push(`import type { CowFeatEntry } from "@/database/packages/dnd35/content/types.ts";`);
  lines.push(``);
  lines.push(`export const COW_FEATS: CowFeatEntry[] = [`);
  for (const entry of deduped.values()) {
    const aptStr = entry.aptitudes.map(quote).join(", ");
    lines.push(`  { feat: ${quote(entry.feat)}, requirements: [], aptitudes: [${aptStr}] },`);
  }
  lines.push(`];`);
  lines.push(``);

  writeGenerated(out, outPath, lines.join("\n"));
}

/** Regenerate cowSpells.ts for a book. Scans all OTHER books' spell references for spells that
 *  have levelEntries matching this book's casting classes. Produces per-class-level entries
 *  so the seed uses the correct level for each class (not the global minimum). */
function regenerateCowSpells(out: Output, book: string) {
  if (!copiesFromCore(book)) return;
  const classes = classReferences(book);

  // Build map: className → aptitude name for classes that have spell lists
  const classToApt = new Map<string, string>();
  for (const { ref } of classes) {
    if (classSpells(ref) && ref.raw?.name) classToApt.set(ref.raw.name, `${ref.raw.name} Spells`);
  }
  // The lists classes draw on (`inheritsFrom`), each its class's aptitude
  const bookInheritedLists = inheritedLists(book);

  // Load this book's own spell names (these don't need COW — they're seeded directly)
  const bookSpellNames = new Set<string>();
  const bookSpellPath = join(REFERENCE_DIR, book, "spells.json");
  if (existsSync(bookSpellPath)) {
    const ref = loadReference(bookSpellPath, "spell");
    for (const spell of ref.raw) bookSpellNames.add(spell.name);
  }

  // Scan ALL other books' spell references
  type CowEntry = { spell: string; aptitudes: { aptitude: string; level: number }[] };
  const entries = new Map<string, CowEntry>();
  // The spells an inherited list can take: the base book's and this book's
  const inheritable = new Set<string>();

  // Find the base book (the one defining core classes like Wizard).
  // COW only makes sense for spells from the base book, not siblings.
  const baseBook = referenceBooks().find((b) => classReferences(b).some(({ ref }) => ref.raw?.name === "Wizard"));
  const isBaseBook = book === baseBook;
  for (const otherBook of referenceBooks()) {
    const spellPath = join(REFERENCE_DIR, otherBook, "spells.json");
    if (!existsSync(spellPath)) continue;

    const ref = loadReference(spellPath, "spell");
    for (const spell of ref.raw) {
      const isSameBook = bookSpellNames.has(spell.name);
      const isFromBase = otherBook === baseBook;
      const matchedApts: { aptitude: string; level: number }[] = [];
      const overrideLe = ref.overrides?.[spell.name]?.levelEntries ?? [];
      const levelEntries = [...spell.levelEntries, ...overrideLe];
      for (const le of levelEntries) {
        // Direct class matches: only from the base book (not siblings).
        // Same-book spells are seeded by seedPowers directly.
        // The base book itself never needs COW entries (extensions link via seedPowers).
        if (!isSameBook && !isBaseBook && isFromBase) {
          const aptName = classToApt.get(le.className);
          if (aptName) {
            matchedApts.push({ aptitude: aptName, level: le.level });
          }
        }
      }
      // Inherited spell lists: from the base book + current book only
      if (isSameBook || isFromBase) {
        inheritable.add(spell.name);
        for (const { aptitude, list } of bookInheritedLists) {
          const level = inheritedLevel(spell, levelEntries, list);
          if (level !== undefined) matchedApts.push({ aptitude, level });
        }
      }

      if (matchedApts.length === 0) continue;

      const existing = entries.get(spell.name);
      if (existing) {
        // Merge aptitudes (deduplicate by aptitude name)
        for (const apt of matchedApts) {
          if (!existing.aptitudes.some((a) => a.aptitude === apt.aptitude)) {
            existing.aptitudes.push(apt);
          }
        }
      } else {
        entries.set(spell.name, { spell: spell.name, aptitudes: matchedApts });
      }
    }
  }

  // A list's additions, at their level there
  for (const { aptitude, list } of bookInheritedLists) {
    for (const [level, names] of Object.entries(list.additions ?? {})) {
      for (const name of names) {
        if (!inheritable.has(name)) throw new Error(`${aptitude}: "${name}" is neither a core spell nor the book's`);
        const entry = entries.get(name) ?? { spell: name, aptitudes: [] };
        entry.aptitudes = [
          ...entry.aptitudes.filter((a) => a.aptitude !== aptitude),
          { aptitude, level: Number(level) },
        ];
        entries.set(name, entry);
      }
    }
  }

  const outPath = join(out.dir, book, "cowSpells.ts");

  const lines: string[] = [];
  lines.push(GENERATED_HEADER);
  lines.push(`import type { CowSpellEntry } from "@/database/packages/dnd35/content/types.ts";`);
  lines.push(``);
  lines.push(`export const COW_SPELLS: CowSpellEntry[] = [`);
  for (const entry of entries.values()) {
    const aptStr = entry.aptitudes.map((a) => `{ aptitude: ${quote(a.aptitude)}, level: ${a.level} }`).join(", ");
    lines.push(`  { spell: ${quote(entry.spell)}, aptitudes: [${aptStr}] },`);
  }
  lines.push(`];`);
  lines.push(``);

  writeGenerated(out, outPath, lines.join("\n"));
}

/** Regenerate cowSpells.ts for ALL books that have casting classes. Called after spell generation
 *  since new spells in any book may change COW entries in other books. */
function regenerateCowSpellsAllBooks(out: Output) {
  for (const book of referenceBooks()) regenerateCowSpells(out, book);
}

function regenerateFavoredEnemyFeats(out: Output, book: string) {
  if (book !== "srd") return;

  writeGenerated(out, join(out.dir, book, "feats", "favoredEnemy.ts"), generateFavoredEnemyFeats());
}

/** Regenerate feats/index.ts for a book from all .ts files in feats/ and classes/index.ts. */
function regenerateFeatIndex(out: Output, book: string) {
  const featDir = join(out.dir, book, "feats");

  // Discover all .ts files in feats/ (excluding index.ts and classes/)
  type FeatFileExport = { file: string; exports: string[] };
  const featFiles: FeatFileExport[] = [];
  try {
    for (const file of readdirSync(featDir).sort()) {
      if (!file.endsWith(".ts") || file === "index.ts") continue;
      const content = readFileSync(join(featDir, file), "utf-8");
      const exports: string[] = [];
      for (const m of content.matchAll(/export const (\w+): FeatSeed\[\]/g)) {
        exports.push(m[1]);
      }
      if (exports.length > 0) featFiles.push({ file, exports });
    }
  } catch {
    // dir doesn't exist
  }

  const allFeatExports = featFiles.flatMap((f) => f.exports);

  // Check if class feat index exists
  const classFeatIndexPath = join(featDir, "classes", "index.ts");
  const hasClassFeats = existsSync(classFeatIndexPath);

  if (allFeatExports.length === 0 && !hasClassFeats) return;

  const lines: string[] = [];
  lines.push(GENERATED_HEADER);
  lines.push(`import type { FeatSeed } from "@/database/packages/dnd35/content/types.ts";`);
  lines.push(``);

  // Re-exports from each feat file
  for (const { file, exports } of featFiles) {
    const slug = file.replace(".ts", "");
    lines.push(`export {`);
    for (const name of exports) {
      lines.push(`  ${name},`);
    }
    lines.push(`} from "./${slug}.ts";`);
    lines.push(``);
  }

  if (hasClassFeats) {
    lines.push(`export { ALL_CLASS_FEATS } from "./classes/index.ts";`);
    lines.push(``);
  }

  // Build aggregate exports
  if (allFeatExports.length > 0 || hasClassFeats) {
    // Need direct imports for spreading
    for (const { file, exports } of featFiles) {
      const slug = file.replace(".ts", "");
      lines.push(`import {`);
      for (const name of exports) {
        lines.push(`  ${name} as _${name},`);
      }
      lines.push(`} from "./${slug}.ts";`);
    }
    if (hasClassFeats) {
      lines.push(`import { ALL_CLASS_FEATS as _ALL_CLASS_FEATS } from "./classes/index.ts";`);
    }
    lines.push(``);

    // ALL_STANDALONE_FEATS: all non-class feats (empty array if none)
    const standalone = allFeatExports.map((name) => `..._${name}`);
    lines.push(...listExport("ALL_STANDALONE_FEATS", "FeatSeed", standalone));
    // ALL_FEATS: everything (standalone + class feats)
    lines.push(
      ...listExport("ALL_FEATS", "FeatSeed", hasClassFeats ? [...standalone, "..._ALL_CLASS_FEATS"] : standalone),
    );
  }

  const outPath = join(featDir, "index.ts");
  writeGenerated(out, outPath, lines.join("\n"));
}

function generateClass(out: Output, ref: ClassReference, book: string) {
  const slug = toCamelCase(ref.raw.name);
  const classPath = join(out.dir, book, "classes", `${slug}.ts`);
  const featPath = join(out.dir, book, "feats", "classes", `${slug}.ts`);

  if (ref.overrides?.skip) {
    // A class left out of the seed: its files go, and the indexes below leave it out
    rmSync(classPath, { force: true });
    rmSync(featPath, { force: true });
  } else {
    writeGenerated(out, classPath, generateClassSeed(ref));
    writeGenerated(out, featPath, generateClassFeatSeeds(ref));
  }

  regenerateFavoredEnemyFeats(out, book);

  // Regenerate aptitudes.ts for this book (covers books with no standalone feats file)
  regenerateAptitudes(out, book);

  // Regenerate cowFeats.ts for this book (bonus feat pools from bonusFeatLists)
  regenerateCowFeats(out, book);

  // Regenerate cowSpells.ts for this book (cross-book spells needing COW)
  regenerateCowSpells(out, book);

  // Regenerate aggregate index files
  regenerateClassIndex(out, book);
  regenerateClassFeatIndex(out, book);
  regenerateFeatIndex(out, book);

  if (!out.quiet) console.log(`\nDone! Review the generated files and copy to database/packages/dnd35/ when ready.`);
}

/** A book's domains file and its domains' feat pools: those of its domains reference, none for a book without one. */
function generateDomain(out: Output, book: string) {
  const { seeds, poolFeats } = bookDomainSeeds(book);
  if (!out.quiet) console.log(`Built ${seeds.length} domain seeds`);

  const outDir = join(out.dir, book, "domains");
  const dataPath = join(outDir, "data.ts");

  if (seeds.length === 0) {
    // No domains for this book — generate empty array
    writeGenerated(
      out,
      dataPath,
      [
        GENERATED_HEADER,
        `import type { DomainDefinition } from "@/database/packages/dnd35/content/types.ts";`,
        ``,
        `export const ALL_DOMAINS: DomainDefinition[] = [];`,
        ``,
      ].join("\n"),
    );
  } else {
    writeGenerated(out, dataPath, domainsCode(seeds));
  }

  // Generate feat pool feats (e.g. War Domain Weapon) — only for domains in this book
  const domainFeatsPath = join(out.dir, book, "feats", "domainFeats.ts");
  if (poolFeats.length > 0) {
    generateDomainFeatPool(out, poolFeats, book);
  } else if (existsSync(domainFeatsPath)) {
    unlinkSync(domainFeatsPath);
    if (!out.quiet) console.log(`Removed: ${domainFeatsPath}`);
  }

  // Regenerate aptitudes (domain feat pools contribute aptitude names)
  regenerateAptitudes(out, book);
  regenerateFeatIndex(out, book);

  if (!out.quiet) console.log(`\nDone!`);
}

function generateFeat(out: Output, ref: FeatReference, book: string) {
  const featCode = generateFeatSeeds(ref);
  const featPath = join(out.dir, book, "feats", "feats.ts");
  writeGenerated(out, featPath, featCode);

  regenerateFavoredEnemyFeats(out, book);
  regenerateAptitudes(out, book);
  regenerateFeatIndex(out, book);

  if (!out.quiet) console.log(`\nDone! Review the generated file and copy to database/packages/dnd35/ when ready.`);
}

/** Regenerate spells/index.ts for a book from existing level .ts files. */
function regenerateSpellIndex(out: Output, book: string) {
  const spellDir = join(out.dir, book, "spells");
  let allFiles: string[];
  try {
    allFiles = readdirSync(spellDir);
  } catch {
    return; // no spells for this book
  }

  // Match cantrips.ts and level*.ts (the standard spell level files)
  const levelFiles: { file: string; level: number; constName: string }[] = [];

  if (allFiles.includes("cantrips.ts")) {
    levelFiles.push({ file: "cantrips.ts", level: 0, constName: "CANTRIPS" });
  }
  for (let i = 1; i <= 9; i++) {
    const fname = `level${i}.ts`;
    if (allFiles.includes(fname)) {
      levelFiles.push({ file: fname, level: i, constName: `LEVEL_${i}_SPELLS` });
    }
  }

  if (levelFiles.length === 0) return;

  const lines = [
    ...indexHead("SpellSeed", levelFiles),
    ...listExport(
      "ALL_SPELLS",
      "SpellSeed",
      levelFiles.map((lf) => `...${lf.constName}.map((p) => ({ ...p, level: ${lf.level} }))`),
    ),
  ];

  const outPath = join(spellDir, "index.ts");
  writeGenerated(out, outPath, lines.join("\n"));
}

function generateSpell(out: Output, ref: SpellReference, book: string) {
  const { spells } = buildSpellSeeds(ref, book);
  if (!out.quiet) console.log(`Built ${spells.length} spell seeds`);

  // Generate .ts files per level
  const files = generateSpellFiles(spells);
  const spellDir = join(out.dir, book, "spells");

  // Remove stale level files that won't be regenerated (e.g. cantrips.ts when no level-0 spells)
  const LEVEL_FILES = ["cantrips.ts", ...Array.from({ length: 9 }, (_, i) => `level${i + 1}.ts`)];
  for (const f of LEVEL_FILES) {
    if (!files.has(f)) {
      try {
        unlinkSync(join(spellDir, f));
      } catch {
        // doesn't exist
      }
    }
  }

  for (const [filename, code] of files) {
    const filePath = join(spellDir, filename);
    writeGenerated(out, filePath, code);
  }

  regenerateSpellIndex(out, book);

  // Regenerate cowSpells.ts for ALL books (new spells in this book may change COW entries elsewhere)
  regenerateCowSpellsAllBooks(out);

  if (!out.quiet) console.log(`\nDone! Review the generated files and copy to database/packages/dnd35/ when ready.`);
}

/**
 * Writes a file of items, `constName`: each its name and description, then the lines `fields` gives. `uses` are the
 * builders it takes from content/items.ts.
 */
function writeItemFile<T extends { name: string; description: string }>(
  out: Output,
  path: string,
  constName: string,
  uses: string[],
  items: T[],
  fields: (item: T) => string[],
) {
  const lines = [
    GENERATED_HEADER,
    `import type { ItemDef } from "@/database/packages/dnd35/content/types.ts";`,
    ...importLines(new Set(uses), ITEM_IMPORTS),
    ``,
    `export const ${constName}: ItemDef[] = [`,
    ...items.flatMap((item) => [
      `  {`,
      `    name: ${quote(item.name)},`,
      `    description: ${quote(item.description)},`,
      ...fields(item).map((line) => `    ${line}`),
      `  },`,
    ]),
    `];`,
    ``,
  ];
  writeGenerated(out, path, lines.join("\n"));
}

function generateArmorFile(
  out: Output,
  path: string,
  constName: string,
  items: ReturnType<typeof buildItemSeeds>["armor"],
) {
  writeItemFile(out, path, constName, ["armorProperties", ...items.map((a) => getArmorProf(a.name))], items, (a) => [
    `weight: ${quote(a.weight)}, costGp: ${quote(a.costGp)}, type: "Armor", slot: "Torso",`,
    `requirements: ${getArmorProf(a.name)},`,
    `properties: armorProperties(${quote(a.name)}),`,
  ]);
}

function generateGoodsFile(
  out: Output,
  path: string,
  constName: string,
  items: ReturnType<typeof buildItemSeeds>["goods"],
) {
  writeItemFile(out, path, constName, [], items, (g) => [
    `weight: ${quote(g.weight)}, costGp: ${quote(g.costGp)}, type: "Other", slot: "Other",`,
    `properties: [],`,
  ]);
}

function generateMagicItemFile(
  out: Output,
  path: string,
  constName: string,
  items: ReturnType<typeof buildMagicItemSeeds>[keyof ReturnType<typeof buildMagicItemSeeds>],
) {
  // A template's requirements are the proficiency with it, by its category
  const proficiency = (item: (typeof items)[number]) =>
    armorProficiencyOf(item.properties.find((property) => property.type === ARMOR_PROFICIENCY)?.value);
  const uses = items.filter((item) => item.isTemplate).map(proficiency);
  writeItemFile(out, path, constName, uses, items, (item) => [
    `weight: ${quote(item.weight)}, costGp: ${quote(item.costGp)}, type: ${quote(item.type)},${item.slot ? ` slot: ${quote(item.slot)},` : ""}`,
    ...(item.isTemplate ? [`isTemplate: true,`, `requirements: ${proficiency(item)},`] : []),
    ...(item.sourceItem ? [`sourceItem: ${quote(item.sourceItem)},`] : []),
    ...(item.properties.length > 0
      ? [`properties: [`, ...item.properties.map((p) => `  ${stringifyProperty(p)},`), `],`]
      : [`properties: [],`]),
    ...listField("modifiers", (item.modifiers ?? []).map(stringifyModifier), ""),
  ]);
}

function generateMagicItem(out: Output, ref: MagicItemReference, book: string, referenceDir: string) {
  const seeds = buildMagicItemSeeds(ref, baseItemWeights(referenceDir));
  const outDir = join(out.dir, book, "items");

  const files: [
    string,
    string,
    ReturnType<typeof buildMagicItemSeeds>[keyof ReturnType<typeof buildMagicItemSeeds>],
  ][] = [
    ["magic-armor.ts", "MAGIC_ARMOR", seeds.magicArmor],
    ["magic-shields.ts", "MAGIC_SHIELDS", seeds.magicShields],
    ["magic-weapons.ts", "MAGIC_WEAPONS", seeds.magicWeapons],
    ["wondrous-items.ts", "WONDROUS_ITEMS", seeds.wondrousItems],
    ["rings.ts", "RINGS", seeds.rings],
    ["rods.ts", "RODS", seeds.rods],
    ["staffs.ts", "STAFFS", seeds.staffs],
  ];

  for (const [filename, constName, items] of files) {
    generateMagicItemFile(out, join(outDir, filename), constName, items);
  }

  // Update index.ts to include magic item re-exports
  generateItemIndexWithMagic(out, outDir);

  if (!out.quiet)
    console.log(
      `\nDone! Generated ${seeds.magicArmor.length} magic armor, ${seeds.magicShields.length} magic shields, ${seeds.magicWeapons.length} magic weapons`,
    );
  if (!out.quiet)
    console.log(
      `  ${seeds.wondrousItems.length} wondrous items, ${seeds.rings.length} rings, ${seeds.rods.length} rods, ${seeds.staffs.length} staffs`,
    );
}

function generateShieldFile(
  out: Output,
  path: string,
  constName: string,
  items: ReturnType<typeof buildItemSeeds>["shields"],
) {
  writeItemFile(out, path, constName, ["shieldProperties", ...items.map((s) => getShieldProf(s.name))], items, (s) => [
    `weight: ${quote(s.weight)}, costGp: ${quote(s.costGp)}, type: "Shield", slot: "Off Hand",`,
    `requirements: ${getShieldProf(s.name)},`,
    `properties: shieldProperties(${quote(s.name)}),`,
  ]);
}

function generateWeaponFile(
  out: Output,
  path: string,
  constName: string,
  weapons: ReturnType<typeof buildItemSeeds>["simpleWeapons"],
  profFn: string,
) {
  writeItemFile(out, path, constName, [profFn, "weaponProperties"], weapons, (w) => [
    `weight: ${quote(w.weight)}, costGp: ${quote(w.costGp)}, type: "Weapon",`,
    `requirements: ${profFn}(${quote(w.name)}),`,
    `properties: weaponProperties(${quote(w.name)}),`,
  ]);
}

function generateItem(out: Output, ref: ItemReference, book: string) {
  const seeds = buildItemSeeds(ref);
  const outDir = join(out.dir, book, "items");

  // weapons.ts
  generateWeaponFile(out, join(outDir, "weapons.ts"), "SIMPLE_WEAPONS", seeds.simpleWeapons, "simple");
  generateWeaponFile(out, join(outDir, "martial.ts"), "MARTIAL_WEAPONS", seeds.martialWeapons, "martial");
  generateWeaponFile(out, join(outDir, "exotic.ts"), "EXOTIC_WEAPONS", seeds.exoticWeapons, "exotic");

  // armor.ts
  generateArmorFile(out, join(outDir, "armor.ts"), "ARMOR", seeds.armor);

  // shields.ts
  generateShieldFile(out, join(outDir, "shields.ts"), "SHIELDS", seeds.shields);

  // goods.ts
  generateGoodsFile(out, join(outDir, "goods.ts"), "GOODS", seeds.goods);

  // index.ts
  generateItemIndex(out, outDir);

  if (!out.quiet)
    console.log(
      `\nDone! Generated ${seeds.simpleWeapons.length} simple, ${seeds.martialWeapons.length} martial, ${seeds.exoticWeapons.length} exotic weapons`,
    );
  if (!out.quiet)
    console.log(`  ${seeds.armor.length} armor, ${seeds.shields.length} shields, ${seeds.goods.length} goods`);
}

/**
 * Runs a generation in a copy of `dir`, which takes `dir`'s place only when the generation reports no failure: a failed
 * one leaves `dir` as it was rather than half-written. The copy sits next to `dir`, so the swap is a rename, and one
 * generation runs on `dir` at a time.
 */
export function generateAtomically(dir: string, generate: (copy: string) => string[]): string[] {
  const copy = `${dir}.next`;
  const previous = `${dir}.previous`;
  const lock = `${dir}.lock`;
  const lockFd = takeLock(lock);
  try {
    // A run killed mid-swap left the tree only as `previous`
    if (!existsSync(dir) && existsSync(previous)) renameSync(previous, dir);
    rmSync(copy, { recursive: true, force: true });
    rmSync(previous, { recursive: true, force: true });
    cpSync(dir, copy, { recursive: true });
    const failures = generate(copy);
    if (failures.length === 0) {
      renameSync(dir, previous);
      try {
        renameSync(copy, dir);
      } catch (error) {
        renameSync(previous, dir);
        throw error;
      }
      rmSync(previous, { recursive: true, force: true });
    }
    return failures;
  } finally {
    rmSync(copy, { recursive: true, force: true });
    closeSync(lockFd);
    rmSync(lock, { force: true });
  }
}

export function generateRef(out: Output, jsonPath: string, bookOverride?: string) {
  const meta = JSON.parse(readFileSync(jsonPath, "utf-8"))._meta;
  if (!meta) throw new Error(`Invalid reference file: missing _meta in ${jsonPath}`);
  const book = bookOverride ?? meta.book;

  switch (meta.type) {
    case "class":
      generateClass(out, loadReference(jsonPath, "class"), book);
      break;
    case "feat":
      generateFeat(out, loadReference(jsonPath, "feat"), book);
      break;
    case "spell":
      generateSpell(out, loadReference(jsonPath, "spell"), book);
      break;
    case "wizardSchool":
      generateWizardSchool(out, loadReference(jsonPath, "wizardSchool"), book);
      break;
    case "domain":
      generateDomain(out, book);
      break;
    case "race":
      generateRace(out, loadReference(jsonPath, "race"), book);
      break;
    case "item":
      generateItem(out, loadReference(jsonPath, "item"), book);
      break;
    case "magicItem":
      generateMagicItem(out, loadReference(jsonPath, "magicItem"), book, dirname(jsonPath));
      break;
    default:
      throw new Error(
        `Unknown type: ${meta.type}. Supported: class, feat, spell, wizardSchool, domain, race, item, magicItem`,
      );
  }
  if (book !== "srd") regenerateBookIndex(out, book);
}

/**
 * Regenerates every reference (of a book, type or name, when given) into `outDir`, then each book's domains unless a
 * name picks one reference. A reference that fails doesn't stop the others: the failures are returned.
 */
export function generateAll(
  { bookFilter, typeFilter, nameFilter }: ReturnType<typeof parseCliArgs>,
  outDir: string,
): string[] {
  const refs = discoverRefs().filter(
    (r) =>
      (!bookFilter || r.book === bookFilter) &&
      (!typeFilter || r.type === typeFilter) &&
      (!nameFilter || basename(r.path, ".json").toLowerCase() === nameFilter),
  );

  const out: Output = { dir: outDir, quiet: true };
  const failures: string[] = [];
  const generate = (path: string, book?: string) => {
    try {
      generateRef(out, path, book);
    } catch (error) {
      failures.push(
        `${relative(REFERENCE_DIR, path)}${book ? ` (${book})` : ""}: ${error instanceof Error ? error.message : error}`,
      );
    }
  };
  // Each book with spells gets its domains file, an empty one when it has no domains reference, and its index
  for (const ref of refs.filter((r) => r.type !== "domain")) generate(ref.path);
  if (typeFilter === "domain" || (!typeFilter && !nameFilter)) {
    for (const book of referenceBooks()) {
      if (!existsSync(join(REFERENCE_DIR, book, "spells.json")) || (bookFilter && book !== bookFilter)) continue;
      try {
        generateDomain(out, book);
        if (book !== "srd") regenerateBookIndex(out, book);
      } catch (error) {
        failures.push(`${book}/domains.json: ${error instanceof Error ? error.message : error}`);
      }
    }
  }
  return failures;
}
