#!/usr/bin/env bun
/**
 * Usage:
 *   bun --env-file=.env.production run scripts/ops/diff/diff-prod.ts
 *
 *   # With content diff against a fresh reference DB:
 *   REFERENCE_DATABASE_URL=postgresql://devuser:devpass@localhost:5433/arkyvree_test \
 *     bun --env-file=.env.production run scripts/ops/diff/diff-prod.ts
 *
 *   # Emit SQL to reconcile target with reference (field drifts only):
 *   REFERENCE_DATABASE_URL=... \
 *     bun --env-file=.env.production run scripts/ops/diff/diff-prod.ts --emit-sql > sync.sql
 *
 * READ-ONLY (unless you run the emitted SQL). Compares a remote database
 * (typically production) against the current codebase and optionally a
 * freshly-seeded reference DB:
 *   1. Schema drift: drizzle.__drizzle_migrations vs drizzle/meta/_journal.json
 *   2. Package drift: rules.content_packages vs database/packages/registry.ts
 *   3. Content drift (if REFERENCE_DATABASE_URL set): for every base ruleset
 *      and extension, every row the seeds write (content.ts), compared
 *      between reference and target.
 */
import { readFileSync } from "node:fs";

import { Pool, type PoolClient } from "pg";

import { registry } from "@/database/packages/registry.ts";
import { planPackages } from "@/database/packages/runner.ts";

import { diffContent, LABELLED_COLUMNS, type Query } from "./content.ts";
import { renderHuman, renderSql } from "./rows.ts";

const referenceConnectionString = process.env.REFERENCE_DATABASE_URL;
const emitSql = process.argv.includes("--emit-sql");

/** A pool client's queries, as the content diff runs them. */
function queryOf(client: PoolClient): Query {
  return async (text, params) => (await client.query(text, params)).rows;
}

/**
 * Prints how the target's content differs from the reference's: for a person, or with `--emit-sql` as the UPDATEs
 * that bring drifted fields in line (rows on one side only stay comments, for manual handling). Whether any differs.
 */
async function reportContentDrift(target: Query, reference: Query): Promise<boolean> {
  const { onlyInTarget, onlyInReference, drifted } = await diffContent(target, reference);
  if (emitSql) {
    console.log(`-- Generated by scripts/ops/diff/diff-prod.ts --emit-sql`);
    console.log(`-- Review before running. Only field-drift UPDATEs are emitted;`);
    console.log(`-- rows only on one side are listed as comments and require manual handling.`);
    console.log(`BEGIN;`);
    for (const name of onlyInTarget)
      console.log(`\n-- ${name}: only in target (reference missing this ruleset) — skipped`);
    for (const name of onlyInReference) {
      console.log(
        `\n-- ${name}: only in reference (target missing this ruleset) — skipped (INSERT would need FK remap)`,
      );
    }
    for (const { ruleset, tables } of drifted) {
      console.log(`\n-- ### ${ruleset}`);
      for (const { table, diff } of tables)
        for (const line of renderSql(table, diff, LABELLED_COLUMNS[table])) console.log(line);
    }
    console.log(`\nCOMMIT;`);
  } else {
    console.log("## Content drift\n");
    for (const name of onlyInTarget)
      console.log(`### ${name}\n  only in target — reference DB is missing this ruleset\n`);
    for (const name of onlyInReference)
      console.log(`### ${name}\n  only in reference — target is missing this ruleset\n`);
    for (const { ruleset, tables } of drifted) {
      console.log(`### ${ruleset}\n`);
      for (const { table, diff } of tables) {
        console.log(`  ${table}:`);
        for (const line of renderHuman(diff)) console.log(`    ${line}`);
        console.log();
      }
    }
  }
  const drift = onlyInTarget.length + onlyInReference.length + drifted.length > 0;
  if (!drift && !emitSql) console.log("No content drift.\n");
  return drift;
}

async function main() {
  const connectionString = process.env.DATABASE_URL;
  if (!connectionString) {
    console.error("DATABASE_URL not set — run with --env-file=.env.production");
    process.exit(1);
  }

  const pool = new Pool({ connectionString });
  const client = await pool.connect();
  let hasDrift = false;
  let failed = false;

  try {
    if (!emitSql) {
      // ── 1. Schema drift ──
      console.log("## Schema drift\n");

      const journal = JSON.parse(readFileSync("./drizzle/meta/_journal.json", "utf8")) as {
        entries: { idx: number; tag: string; when: number }[];
      };
      const codeMigrations = journal.entries.map((e) => ({ tag: e.tag, when: e.when }));

      const { rows: applied } = await client.query<{ created_at: string }>(
        `select created_at from drizzle.__drizzle_migrations order by created_at`,
      );

      const appliedWhens = new Set(applied.map((r) => Number(r.created_at)));
      const codeWhens = new Set(codeMigrations.map((m) => m.when));

      const missingOnRemote = codeMigrations.filter((m) => !appliedWhens.has(m.when));
      const extraOnRemote = applied.map((r) => Number(r.created_at)).filter((w) => !codeWhens.has(w));

      console.log(`Code migrations:   ${codeMigrations.length}`);
      console.log(`Remote migrations: ${applied.length}`);

      if (missingOnRemote.length === 0 && extraOnRemote.length === 0) {
        console.log(`Status: in sync`);
      } else {
        hasDrift = true;
        if (missingOnRemote.length > 0) {
          console.log(`\nIn code but not applied on remote (${missingOnRemote.length}):`);
          for (const m of missingOnRemote) console.log(`  - ${m.tag}`);
        }
        if (extraOnRemote.length > 0) {
          console.log(`\nApplied on remote but not in code (${extraOnRemote.length}):`);
          for (const w of extraOnRemote) console.log(`  - ${new Date(w).toISOString()}`);
        }
      }
      console.log();

      // ── 2. Package drift ──
      console.log("## Package drift\n");

      const { rows: remotePackages } = await client.query<{
        name: string;
        type: string;
        version: number;
        applied_at: string;
      }>(`select name, type, version, applied_at from rules.content_packages order by name`);

      const remoteMap = new Map(remotePackages.map((p) => [p.name, p]));
      // What the next deploy's runner does: it applies no package while one has a problem.
      const { plans, problems } = planPackages(registry, new Map(remotePackages.map((p) => [p.name, p.version])));
      const codeMap = new Map([
        ...registry.map((p): [string, number | undefined] => [p.name, undefined]),
        ...plans.map((p): [string, number | undefined] => [p.pkg.name, p.version]),
      ]);
      const blocked = problems.size > 0;
      const allNames = [...new Set([...remoteMap.keys(), ...codeMap.keys()])].sort();

      const pad = Math.max(...allNames.map((n) => n.length), 4);
      console.log(`${"name".padEnd(pad)}  remote  code  status`);
      console.log(`${"-".repeat(pad)}  ------  ----  ------`);

      for (const name of allNames) {
        const r = remoteMap.get(name);
        const codeVersion = codeMap.get(name);
        const problem = problems.get(name);
        const rv = r ? `v${r.version}` : "—";
        const cv = codeVersion !== undefined ? `v${codeVersion}` : "—";
        let status: string;
        if (problem) {
          status = `next deploy will be REFUSED (${problem.join("; ")})`;
          hasDrift = true;
        } else if (!r) {
          status = blocked
            ? "missing on remote (blocked: the next deploy applies no package)"
            : "missing on remote (next deploy will install)";
          hasDrift = true;
        } else if (codeVersion === undefined) {
          status = "on remote but not in code";
          hasDrift = true;
        } else if (r.version === codeVersion) {
          status = "in sync";
        } else if (r.version < codeVersion) {
          status = blocked
            ? "behind (blocked: the next deploy applies no package)"
            : `next deploy will upgrade (v${r.version} -> v${codeVersion})`;
          hasDrift = true;
        } else {
          status = `remote ahead of code (v${r.version} > v${codeVersion})`;
          hasDrift = true;
        }
        console.log(`${name.padEnd(pad)}  ${rv.padEnd(6)}  ${cv.padEnd(4)}  ${status}`);
      }
      console.log();
    }

    // ── 3. Content drift ──
    if (referenceConnectionString) {
      const refPool = new Pool({ connectionString: referenceConnectionString });
      const refClient = await refPool.connect();
      try {
        if (await reportContentDrift(queryOf(client), queryOf(refClient))) hasDrift = true;
      } finally {
        refClient.release();
        await refPool.end();
      }
    } else if (emitSql) {
      console.error("--emit-sql requires REFERENCE_DATABASE_URL");
      failed = true;
    } else {
      console.log("## Content drift\n");
      console.log("Skipped — set REFERENCE_DATABASE_URL to a freshly-seeded DB");
      console.log("(e.g. run `bun test:db:reset` then point at arkyvree_test).");
      console.log();
    }
  } finally {
    client.release();
    await pool.end();
  }

  // In SQL-emit mode, drift is the expected output, not a failure: only an error exits non-zero
  process.exit(failed || (!emitSql && hasDrift) ? 1 : 0);
}

await main();
