/** The skills the parser recognizes in feat and class text, and the Skill Focus feats are made for. */
export const SKILL_NAMES = [
  "Appraise",
  "Balance",
  "Bluff",
  "Climb",
  "Concentration",
  "Craft",
  "Decipher Script",
  "Diplomacy",
  "Disable Device",
  "Disguise",
  "Escape Artist",
  "Forgery",
  "Gather Information",
  "Handle Animal",
  "Heal",
  "Hide",
  "Intimidate",
  "Jump",
  "Knowledge (Arcana)",
  "Knowledge (Architecture and Engineering)",
  "Knowledge (Dungeoneering)",
  "Knowledge (Geography)",
  "Knowledge (History)",
  "Knowledge (Local)",
  "Knowledge (Nature)",
  "Knowledge (Nobility and Royalty)",
  "Knowledge (Psionics)",
  "Knowledge (Religion)",
  "Knowledge (The Planes)",
  "Listen",
  "Move Silently",
  "Open Lock",
  "Perform",
  "Profession",
  "Ride",
  "Search",
  "Sense Motive",
  "Sleight of Hand",
  "Spellcraft",
  "Spot",
  "Survival",
  "Swim",
  "Tumble",
  "Use Magic Device",
  "Use Rope",
];
