export const ARMOR_PROFICIENCY = "ARMOR_PROFICIENCY";
export const ARMOR_TYPE = "ARMOR_TYPE";
export const ARMOR_MAX_DEX = "ARMOR_MAX_DEX";
export const ARMOR_AC_BONUS = "ARMOR_AC_BONUS";
export const ARMOR_CHECK_PENALTY = "ARMOR_CHECK_PENALTY";
