export const DAMAGE_TYPE = "DAMAGE_TYPE";
export const ITEM_MADE_OF = "ITEM_MADE_OF";
export const ITEM_HAS_CHARGES = "ITEM_HAS_CHARGES";
export const ITEM_SPELL_FAILURE = "ITEM_SPELL_FAILURE";
export const ITEM_MASTERWORK = "ITEM_MASTERWORK";
export const MAGIC_AURA = "MAGIC_AURA";
export const MAGIC_CASTER_LEVEL = "MAGIC_CASTER_LEVEL";