export const WEAPON_PROFICIENCY = "WEAPON_PROFICIENCY";
export const WEAPON_FAMILY = "WEAPON_FAMILY";
export const WEAPON_BASE_DAMAGE = "WEAPON_BASE_DAMAGE";
export const WEAPON_CRITICAL_RANGE = "WEAPON_CRITICAL_RANGE"; // 0 = 20, 1 = 19, etc.
export const WEAPON_CRITICAL_MULTIPLIER = "WEAPON_CRITICAL_MULTIPLIER";
export const WEAPON_MIGHTY = "WEAPON_MIGHTY";
export const WEAPON_RANGE = "WEAPON_RANGE";
export const WEAPON_REACH = "WEAPON_REACH";
export const WEAPON_SIZE = "WEAPON_SIZE";
export const WEAPON_FINESSABLE = "WEAPON_FINESSABLE";
export const WEAPON_TYPE = "WEAPON_TYPE";
