/** The repositories' shared instances, each wrapped in the request cache (`withRequestCache`). */

import { emailVerificationsInAccount, passwordResetsInAccount } from "@/drizzle/schema.ts";

import AccountCodesRepository from "./accounts/AccountCodesRepository.ts";
import OauthAccountsRepository from "./accounts/OauthAccountsRepository.ts";
import SessionsRepository from "./accounts/SessionsRepository.ts";
import UsersRepository from "./accounts/UsersRepository.ts";
import ActivitiesRepository from "./activities/ActivitiesRepository.ts";
import AttachmentsRepository from "./attachments/AttachmentsRepository.ts";
import BlobsRepository from "./attachments/BlobsRepository.ts";
import CampaignsRepository from "./campaigns/CampaignsRepository.ts";
import InvitesRepository from "./campaigns/InvitesRepository.ts";
import PlayerCharactersRepository from "./campaigns/PlayerCharactersRepository.ts";
import PlayersRepository from "./campaigns/PlayersRepository.ts";
import CharacterAbilitiesRepository from "./characters/CharacterAbilitiesRepository.ts";
import CharacterContributorsRepository from "./characters/CharacterContributorsRepository.ts";
import CharacterInventoryRepository from "./characters/CharacterInventoryRepository.ts";
import CharacterLanguagesRepository from "./characters/CharacterLanguagesRepository.ts";
import CharacterLevelFeatsRepository from "./characters/CharacterLevelFeatsRepository.ts";
import CharacterLevelPowersRepository from "./characters/CharacterLevelPowersRepository.ts";
import CharacterLevelSkillsRepository from "./characters/CharacterLevelSkillsRepository.ts";
import CharacterLevelsRepository from "./characters/CharacterLevelsRepository.ts";
import CharactersRepository from "./characters/CharactersRepository.ts";
import ExportsRepository from "./exports/ExportsRepository.ts";
import NotificationsRepository from "./notifications/NotificationsRepository.ts";
import AbilitiesRepository from "./rulesets/AbilitiesRepository.ts";
import AptitudesRepository from "./rulesets/AptitudesRepository.ts";
import ContributorsRepository from "./rulesets/ContributorsRepository.ts";
import EntitySnapshotsRepository from "./rulesets/EntitySnapshotsRepository.ts";
import FeatsAptitudesRepository from "./rulesets/FeatsAptitudesRepository.ts";
import FeatsRepository from "./rulesets/FeatsRepository.ts";
import ItemsRepository from "./rulesets/ItemsRepository.ts";
import KlassesRepository from "./rulesets/KlassesRepository.ts";
import KlassLevelFeatsRepository from "./rulesets/KlassLevelFeatsRepository.ts";
import KlassLevelPowersRepository from "./rulesets/KlassLevelPowersRepository.ts";
import KlassLevelSavesRepository from "./rulesets/KlassLevelSavesRepository.ts";
import KlassLevelsRepository from "./rulesets/KlassLevelsRepository.ts";
import KlassSkillsRepository from "./rulesets/KlassSkillsRepository.ts";
import LanguagesRepository from "./rulesets/LanguagesRepository.ts";
import MechanicsRepository from "./rulesets/MechanicsRepository.ts";
import ModifiersRepository from "./rulesets/ModifiersRepository.ts";
import PowersAptitudesRepository from "./rulesets/PowersAptitudesRepository.ts";
import PowersRepository from "./rulesets/PowersRepository.ts";
import PropertiesRepository from "./rulesets/PropertiesRepository.ts";
import RacesRepository from "./rulesets/RacesRepository.ts";
import RequirementsRepository from "./rulesets/RequirementsRepository.ts";
import RulesetEntitiesRepository from "./rulesets/RulesetEntitiesRepository.ts";
import RulesetExtensionsRepository from "./rulesets/RulesetExtensionsRepository.ts";
import RulesetsRepository from "./rulesets/RulesetsRepository.ts";
import SavesRepository from "./rulesets/SavesRepository.ts";
import SkillsRepository from "./rulesets/SkillsRepository.ts";
import StarredRulesetsRepository from "./rulesets/StarredRulesetsRepository.ts";
import { withRequestCache } from "./withRequestCache.ts";

export const Abilities = withRequestCache("Abilities", new AbilitiesRepository());
export const Activities = withRequestCache("Activities", new ActivitiesRepository());
export const Aptitudes = withRequestCache("Aptitudes", new AptitudesRepository());
export const Attachments = withRequestCache("Attachments", new AttachmentsRepository());
export const Blobs = withRequestCache("Blobs", new BlobsRepository());
export const Campaigns = withRequestCache("Campaigns", new CampaignsRepository());
export const CharacterAbilities = withRequestCache("CharacterAbilities", new CharacterAbilitiesRepository());
export const CharacterContributors = withRequestCache("CharacterContributors", new CharacterContributorsRepository());
export const CharacterInventory = withRequestCache("CharacterInventory", new CharacterInventoryRepository());
export const CharacterLanguages = withRequestCache("CharacterLanguages", new CharacterLanguagesRepository());
export const CharacterLevelFeats = withRequestCache("CharacterLevelFeats", new CharacterLevelFeatsRepository());
export const CharacterLevelPowers = withRequestCache("CharacterLevelPowers", new CharacterLevelPowersRepository());
export const CharacterLevels = withRequestCache("CharacterLevels", new CharacterLevelsRepository());
export const CharacterLevelSkills = withRequestCache("CharacterLevelSkills", new CharacterLevelSkillsRepository());
export const Characters = withRequestCache("Characters", new CharactersRepository());
export const Contributors = withRequestCache("Contributors", new ContributorsRepository());
export const EmailVerifications = withRequestCache(
  "EmailVerifications",
  new AccountCodesRepository(emailVerificationsInAccount),
);
export const EntitySnapshots = withRequestCache("EntitySnapshots", new EntitySnapshotsRepository(), { skipCow: true });
export const Exports = withRequestCache("Exports", new ExportsRepository());
export const Feats = withRequestCache("Feats", new FeatsRepository());
export const FeatsAptitudes = withRequestCache("FeatsAptitudes", new FeatsAptitudesRepository());
export const Invites = withRequestCache("Invites", new InvitesRepository());
export const Items = withRequestCache("Items", new ItemsRepository());
export const Klasses = withRequestCache("Klasses", new KlassesRepository());
export const KlassLevelFeats = withRequestCache("KlassLevelFeats", new KlassLevelFeatsRepository());
export const KlassLevelPowers = withRequestCache("KlassLevelPowers", new KlassLevelPowersRepository());
export const KlassLevels = withRequestCache("KlassLevels", new KlassLevelsRepository());
export const KlassLevelSaves = withRequestCache("KlassLevelSaves", new KlassLevelSavesRepository());
export const KlassSkills = withRequestCache("KlassSkills", new KlassSkillsRepository());
export const Languages = withRequestCache("Languages", new LanguagesRepository());
export const Mechanics = withRequestCache("Mechanics", new MechanicsRepository());
export const Modifiers = withRequestCache("Modifiers", new ModifiersRepository());
export const Notifications = withRequestCache("Notifications", new NotificationsRepository());
export const OauthAccounts = withRequestCache("OauthAccounts", new OauthAccountsRepository());
export const PasswordResets = withRequestCache("PasswordResets", new AccountCodesRepository(passwordResetsInAccount));
export const PlayerCharacters = withRequestCache("PlayerCharacters", new PlayerCharactersRepository());
export const Players = withRequestCache("Players", new PlayersRepository());
export const Powers = withRequestCache("Powers", new PowersRepository());
export const PowersAptitudes = withRequestCache("PowersAptitudes", new PowersAptitudesRepository());
export const Properties = withRequestCache("Properties", new PropertiesRepository());
export const Races = withRequestCache("Races", new RacesRepository());
export const Requirements = withRequestCache("Requirements", new RequirementsRepository());
export const RulesetEntities = withRequestCache("RulesetEntities", new RulesetEntitiesRepository(), { skipCow: true });
export const RulesetExtensions = withRequestCache("RulesetExtensions", new RulesetExtensionsRepository());
export const Rulesets = withRequestCache("Rulesets", new RulesetsRepository());
export const Saves = withRequestCache("Saves", new SavesRepository());
export const Sessions = withRequestCache("Sessions", new SessionsRepository());
export const Skills = withRequestCache("Skills", new SkillsRepository());
export const StarredRulesets = withRequestCache("StarredRulesets", new StarredRulesetsRepository());
export const Users = withRequestCache("Users", new UsersRepository());
